### ISSUE TITLE
No module named 'unifree'

### ISSUE THREAD

**Issue by StephenGrosjean** [ProjectUnifree/unifree#14]
When running the launch.bat as in the documentation I get this error:

`Traceback (most recent call last):
  File "D:\0-WORK\Unifree\unifree\unifree\free.py", line 8, in <module>
    import unifree
ModuleNotFoundError: No module named 'unifree'`

**Comment by harryarakkal** [comment]
That's odd. Could you try adding `sys.path.insert(0, './')` to the [unifree/free.py file at this location](https://github.com/ProjectUnifree/unifree/blob/9a0703ff5b41c27a019206c6c795988da7864a92/unifree/free.py#L7)?

Let me know if this works

**Comment by StephenGrosjean** [comment]
Like this? 

```
import argparse
import os.path
import platform
import sys
sys.path.insert(0, './')
import unifree
from unifree import utils, log
```

I then have this error, maybe that's something on my side, but all the requirements are satisfied.
```
Unable to start:[OPENAI-KEY] is invalid: [WinError 3] Le chemin d’accès spécifié est introuvable: 'config/'
Traceback (most recent call last):
  File "D:\0-WORK\Unifree\unifree\unifree\free.py", line 23, in run_migration
    config = utils.load_config(config)
  File "D:\0-WORK\Unifree\unifree\.\unifree\utils.py", line 23, in load_config
    for config_file_name in os.listdir("config/"):
FileNotFoundError: [WinError 3] Le chemin d’accès spécifié est introuvable: 'config/'
Unable to start: [OPENAI-KEY] is invalid: [WinError 3] Le chemin d’accès spécifié est introuvable: 'config/'
Traceback (most recent call last):
  File "D:\0-WORK\Unifree\unifree\unifree\free.py", line 23, in run_migration
    config = utils.load_config(config)
  File "D:\0-WORK\Unifree\unifree\.\unifree\utils.py", line 23, in load_config
    for config_file_name in os.listdir("config/"):
FileNotFoundError: [WinError 3] Le chemin d’accès spécifié est introuvable: 'config/'
Traceback (most recent call last):
  File "D:\0-WORK\Unifree\unifree\unifree\free.py", line 23, in run_migration
    config = utils.load_config(config)
  File "D:\0-WORK\Unifree\unifree\.\unifree\utils.py", line 23, in load_config
    for config_file_name in os.listdir("config/"):
FileNotFoundError: [WinError 3] Le chemin d’accès spécifié est introuvable: 'config/'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\0-WORK\Unifree\unifree\unifree\free.py", line 120, in <module>
    migrate()
  File "D:\0-WORK\Unifree\unifree\unifree\free.py", line 113, in migrate
    status_code = run_migration(
  File "D:\0-WORK\Unifree\unifree\unifree\free.py", line 28, in run_migration
    return os.EX_CONFIG
AttributeError: module 'os' has no attribute 'EX_CONFIG'

D:\0-WORK\Unifree\unifree>exit /b
```

**Comment by pRoFlT** [comment]
Same for me " ModuleNotFoundError: No module named 'unifree' ", Running windows.

**Comment by bshikin** [comment]
To copy for Discord: 

launch.bat has 1 issue i found and im also getting a import unifree no module error. 
```
set CONFIG_NAME=%1
set OPENAI_API_KEY=%2
set ORIGIN_DIR=%3
set DEST_DIR=%3
```

**Comment by bshikin** [comment]
@pRoFlT / @StephenGrosjean PR https://github.com/ProjectUnifree/unifree/pull/26 merged to master, please try again.

Note: I didn't have a windows machine to QA, so if it doesn't work please let us know.
